version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - feelme-api
      - feelme-web
      - fuzzy-api
    networks:
      - nginx-network

  feelme-api:
    build:
      context: ./Golang
      dockerfile: ./Dockerfile
    container_name: feelme-api
    expose:
      - 5000
    restart: "unless-stopped"
    networks:
      - nginx-network

  fuzzy-api:
    build:
      context: './python'
      dockerfile: dockerfile
    container_name: fuzzy-api
    expose:
        - 8000
    restart: unless-stopped
    networks:
      - nginx-network

  feelme-web:
    build:
      context: './web'
      dockerfile: dockerfile
    container_name: feelme-web
    expose: 
      - 1000
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
  