version: '3.9'
services:
  api:
    image: "feelme/api"
    build:
      context: .
    container_name: feelMe-api
    restart: always
    ports: 
      - "5005:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - feelme_network

networks:
  feelme_network: