name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: cd dotnet
      run:  dotnet restore

    - name: Build
      run: cd dotnet
      run: dotnet build --no-restore

    - name: Test
      run: cd dotnet
      run: dotnet test --no-build --verbosity normal
